/**
 * Normalises a pasted private key string: strips surrounding whitespace,
 * normalises Windows line endings, and ensures a trailing newline.
 */
export function normaliseKey(raw: string): string {
  return raw
    .trim()
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    + "\n";
}

/**
 * Derives the OpenSSH public key string from an OpenSSH private key.
 *
 * Works by parsing the binary OpenSSH private key format directly — the
 * unencrypted public key blob is embedded at the start of the file and
 * requires no OpenSSL/crypto calls at all. This avoids OpenSSL 3 decoder
 * compatibility issues with the OpenSSH key format.
 *
 * Supports ed25519 keys (recommended: ssh-keygen -t ed25519 -C aura-cluster-key).
 * Passphrase-protected keys are not supported.
 */
export function sshPublicKeyFromPrivate(privateKeyPem: string): string {
  const normalised = normaliseKey(privateKeyPem);

  // Detect format.
  if (normalised.includes("BEGIN OPENSSH PRIVATE KEY")) {
    return parseOpenSSHFormat(normalised);
  }

  // PEM/PKCS8 fallback via Node.js crypto (RSA, EC in traditional PEM form).
  try {
    const { createPrivateKey, createPublicKey } = require("crypto");
    const privKey = createPrivateKey(normalised);
    const keyType = privKey.asymmetricKeyType as string;

    if (keyType === "ed25519") {
      const pubKey = createPublicKey(privKey);
      const spkiDer = pubKey.export({ type: "spki", format: "der" }) as Buffer;
      const rawKey = spkiDer.slice(-32);
      const typeBuf = Buffer.from("ssh-ed25519");
      const wire = Buffer.allocUnsafe(4 + typeBuf.length + 4 + rawKey.length);
      wire.writeUInt32BE(typeBuf.length, 0);
      typeBuf.copy(wire, 4);
      wire.writeUInt32BE(rawKey.length, 4 + typeBuf.length);
      rawKey.copy(wire, 4 + typeBuf.length + 4);
      return `ssh-ed25519 ${wire.toString("base64")} aura-cluster-key`;
    }

    if (keyType === "rsa") {
      const pubKey = createPublicKey(privKey);
      const jwk = pubKey.export({ format: "jwk" }) as { n: string; e: string };
      // SSH ssh-rsa wire: string "ssh-rsa" + mpint e + mpint n
      const e = b64UrlToBuffer(jwk.e);
      const n = b64UrlToBuffer(jwk.n);
      const typeBuf = Buffer.from("ssh-rsa");
      const eMpi = encodeMpint(e);
      const nMpi = encodeMpint(n);
      const wire = Buffer.allocUnsafe(4 + typeBuf.length + eMpi.length + nMpi.length);
      let off = 0;
      wire.writeUInt32BE(typeBuf.length, off); off += 4;
      typeBuf.copy(wire, off); off += typeBuf.length;
      eMpi.copy(wire, off); off += eMpi.length;
      nMpi.copy(wire, off);
      return `ssh-rsa ${wire.toString("base64")} aura-cluster-key`;
    }

    throw new Error(
      `Key type "${keyType}" is not supported. Use ed25519 (recommended) or RSA:\n` +
      `  ssh-keygen -t ed25519 -C aura-cluster-key -f ~/.ssh/aura_cluster_key`
    );
  } catch (e: any) {
    if (e.message?.startsWith("Key type")) throw e;
    throw new Error(
      `Could not parse private key: ${e?.message ?? "unknown error"}. ` +
      `Paste the full OpenSSH private key including the -----BEGIN/END----- lines.`
    );
  }
}

/**
 * Parses the OpenSSH wire format and extracts the embedded public key.
 *
 * Format (RFC 4253 + OpenSSH extension):
 *   magic    "openssh-key-v1\0"  (15 bytes)
 *   string   ciphername          ("none" for unencrypted)
 *   string   kdfname             ("none")
 *   string   kdfoptions          (empty)
 *   uint32   number of keys      (1)
 *   string   public key blob     ← this is what we want
 *   string   private key section (encrypted, we skip it)
 *
 * The public key blob is already in SSH wire format identical to .pub files.
 */
function parseOpenSSHFormat(pem: string): string {
  const b64 = pem
    .replace(/-----BEGIN OPENSSH PRIVATE KEY-----/g, "")
    .replace(/-----END OPENSSH PRIVATE KEY-----/g, "")
    .replace(/[\s]/g, "");

  const buf = Buffer.from(b64, "base64");

  // Verify magic: "openssh-key-v1" (14 bytes) + NUL (1 byte) = 15 bytes.
  if (buf.length < 15 || buf.slice(0, 14).toString("ascii") !== "openssh-key-v1") {
    throw new Error(
      "Not a recognised OpenSSH private key. " +
      "Paste the key exactly as generated by ssh-keygen."
    );
  }

  let offset = 15; // skip magic + NUL

  function readStr(): string {
    const len = buf.readUInt32BE(offset);
    offset += 4;
    const s = buf.slice(offset, offset + len).toString("ascii");
    offset += len;
    return s;
  }

  function readBlob(): Buffer {
    const len = buf.readUInt32BE(offset);
    offset += 4;
    const b = buf.slice(offset, offset + len);
    offset += len;
    return b;
  }

  const cipherName = readStr();
  const kdfName = readStr();
  readBlob(); // kdf options — skip
  const numKeys = buf.readUInt32BE(offset); offset += 4;

  if (cipherName !== "none" || kdfName !== "none") {
    throw new Error(
      "Passphrase-protected keys are not supported. " +
      "Generate a key without a passphrase:\n" +
      "  ssh-keygen -t ed25519 -C aura-cluster-key -N '' -f ~/.ssh/aura_cluster_key"
    );
  }
  if (numKeys < 1) {
    throw new Error("No keys found in private key file.");
  }

  // Read public key blob — it IS the SSH wire format used in authorized_keys.
  const pubKeyBlob = readBlob();

  // Extract key type from the blob to validate + build the public key line.
  const keyTypeLen = pubKeyBlob.readUInt32BE(0);
  const keyType = pubKeyBlob.slice(4, 4 + keyTypeLen).toString("ascii");

  const supported = ["ssh-ed25519", "ecdsa-sha2-nistp256", "ecdsa-sha2-nistp384", "ecdsa-sha2-nistp521", "ssh-rsa"];
  if (!supported.includes(keyType)) {
    throw new Error(
      `Key type "${keyType}" is not supported. Use ed25519 (recommended):\n` +
      `  ssh-keygen -t ed25519 -C aura-cluster-key -N '' -f ~/.ssh/aura_cluster_key`
    );
  }

  return `${keyType} ${pubKeyBlob.toString("base64")} aura-cluster-key`;
}

// JWK encodes integers as base64url-without-padding. Decode to a raw byte
// buffer suitable for SSH mpint encoding.
function b64UrlToBuffer(s: string): Buffer {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/") + "==".slice((s.length + 3) % 4);
  return Buffer.from(b64, "base64");
}

// SSH mpint: 4-byte length prefix + the bytes, with a leading 0x00 prepended
// when the high bit of the first byte is set (so the integer is interpreted
// as positive in two's complement).
function encodeMpint(raw: Buffer): Buffer {
  let bytes = raw;
  // Strip leading zeros JWK might leave behind.
  let i = 0;
  while (i < bytes.length - 1 && bytes[i] === 0) i++;
  bytes = bytes.slice(i);
  const needsPad = (bytes[0] & 0x80) !== 0;
  const len = bytes.length + (needsPad ? 1 : 0);
  const out = Buffer.allocUnsafe(4 + len);
  out.writeUInt32BE(len, 0);
  if (needsPad) {
    out[4] = 0;
    bytes.copy(out, 5);
  } else {
    bytes.copy(out, 4);
  }
  return out;
}
