---
- name: restart sssd
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/_supervisor.yml"
  vars:
    svc_name: sssd
    svc_cmd: "/usr/sbin/sssd --interactive --logger=stderr"
    svc_state: restarted
