---
- name: restart munge
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/_supervisor.yml"
  vars:
    svc_name: munge
    svc_cmd: "/usr/sbin/runuser -u {{ munge_user }} -- /usr/sbin/munged --foreground"
    svc_state: restarted
