---
- name: restart slurmctld
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/_supervisor.yml"
  vars:
    svc_name: slurmctld
    svc_cmd: "/usr/sbin/slurmctld -D -f {{ slurm_config_dir }}/slurm.conf"
    svc_state: restarted

- name: restart slurmdbd
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/_supervisor.yml"
  vars:
    svc_name: slurmdbd
    svc_cmd: "/usr/sbin/slurmdbd -D -v"
    svc_state: restarted
