FROM node:20-alpine

RUN apk add --no-cache openssl openssh-client python3 py3-pip git && \
    pip3 install --break-system-packages ansible-core==2.16.* && \
    ansible-galaxy collection install community.mysql ansible.posix community.general

WORKDIR /app
